25/45. Done with list and list-currencies, now file checking and the rest of the commands

diff --git a/xtf b/xtf
--- a/xtf
+++ b/xtf
@@ -5,6 +5,12 @@
 
 export POSIXLY_CORRECT=yes
 export LC_ALL=C
+trader_error="No user found!"
+date_error="No date found"
+currency_error="No currency found"
+file_error="No files found"
+export XTF_PROFIT=20
+# set -x # debugs the script
 
 # zcat "$FILES"
 # same as surrounding it with backticks, but this is better (you can nest $($(...)))
@@ -17,13 +23,34 @@ if [ "$#" = 0 ]
         echo "Use: \"./xtf -h\" or \"./xtf -help\" for more info."
         exit 1
 fi
-check_FILES() {
+check_args() {
     if [ "$1" = "" ]
-    then
-        echo "ERROR: No FILES detected" >&2
-        exit 1
+        then
+            echo "ERROR: $2. Use \"-h\" or \"--help\" for more info." >&2
+            exit 1
     fi
 }
+check_all() {
+    check_args "$TRADER" "$trader_error"
+    check_args "$FILES" "$file_error"
+}
+check_date() {
+    case $1 in
+        [0-9][0-9][0-9][0-9]-[0-9][0-9]-[0-9][0-9]\ [0-2][0-9]-[0-5][0-9]-[0-5][0-9])
+            echo "All good"
+            ;;
+        *)
+            echo "ERROR: Wrong date format. Use \"-h\" or \"--help\" for more info." >&2
+            exit 1
+            ;;
+    esac
+}
+# check_file() {
+#     if "$1" != '' # TODO
+# }
+# error_output() {
+#     # TODO
+# }
 add_file() {
     if [ $file_count = 0 ]
         then
@@ -62,6 +89,8 @@ help() {
     echo "  \"-b DATETIME\" -> considers records before the specified date (non-inclusive)"
     echo "  \"-c CURRENCIES\" -> considers records containing the specified currencies"
     echo ""
+    echo "The date format is: YYYY-MM-DD HH:MM:SS"
+    echo ""
     echo "COMMAND -> can be one of:"
     echo "  \"list\" -> displays a list of records for a specified TRADER"
     echo "  \"list-CURRENCIES\" -> displays a list of sorted records for a CURRENCIES"
@@ -70,18 +99,40 @@ help() {
     echo ""
 }
 list() {
-    if [ "$TRADER" = "" ]
-        then
-            zcat "$FILES" | sort
-            exit 0
-    fi
+    awk -P -F ";" -v user="$TRADER" -v date_after="$DATETIME_AFTER" -v date_before="$DATETIME_BEFORE" -v currencies="$CURRENCIES" ' 
+    {
+        if (currencies != "") {
+            num_of_currencies=split(currencies, currency_list, " ") 
+            # split returns number of values in the array
+        }
+        else {
+            num_of_currencies = 1
+            currency_list[1] = ""
+        }
+        for(i=1; i<=num_of_currencies; i++) {
+            if ($1 == user && ($2 > date_after || date_after == "") && ($2 < date_before || date_before == "") && ($3 == currency_list[i] || currency_list[i] == "")) {
+                print $0
+            }
+        }
+    }'
 }
-list_CURRENCIES() {
-    if [ "$TRADER" = "" ]
-        then
-            echo "$FILES"
-            exit 0
-    fi
+list_currency() {
+    awk -P -F ";" -v user="$TRADER" -v date_after="$DATETIME_AFTER" -v date_before="$DATETIME_BEFORE" -v currencies="$CURRENCIES" ' 
+    {
+        if (currencies != "") {
+            num_of_currencies=split(currencies, currency_list, " ") 
+            # split returns number of values in the array
+        }
+        else {
+            num_of_currencies = 1
+            currency_list[1] = ""
+        }
+        for(i=1; i<=num_of_currencies; i++) {
+            if ($1 == user && ($2 > date_after || date_after == "") && ($2 < date_before || date_before == "") && ($3 == currency_list[i] || currency_list[i] == "")) {
+                print $3
+            }
+        }
+    }' | sort -u
 }
 status() {
     echo status
@@ -90,7 +141,7 @@ profit() {
     echo profit
 }
 COMMAND=list
-command_set=1
+command_set=0
 file_count=0
 currency_count=0
 # Arg parsing
@@ -108,79 +159,79 @@ while [ "$#" -gt 0 ]
             -a)
                 # shifts all args to the left ($2 becomes $1)
                 shift
-                if [ "$1" = "" ]
+                if [ "$DATETIME_AFTER" != "" ]
                     then
-                        echo "ERROR: No parameter passed for argument. Use \"-h\" or \"--help\" for more info." >&2
+                        echo "ERROR: Only one date_after is allowed!" >&2
                         exit 1
                 fi
-
-                DATETIME="$1" # after the date (non-inclusive)
+                check_date "$1"
+                DATETIME_AFTER="$1" # after the date (non-inclusive)
                 shift
                 ;;
 
             -b)
                 shift
-                if [ "$1" = "" ]
+                if [ "$DATETIME_BEFORE" != "" ]
                     then
-                        echo "ERROR: No parameter passed for argument. Use \"-h\" or \"--help\" for more info." >&2
+                        echo "ERROR: Only one date_before is allowed!" >&2
                         exit 1
                 fi
-
-                DATETIME="$1" # before the date (non-inclusive)
+                check_date "$1"
+                DATETIME_BEFORE="$1" # before the date (non-inclusive)
                 shift
                 ;;
 
             -c)
                 shift
-                if [ "$1" = "" ]
-                    then
-                        echo "ERROR: No parameter passed for argument. Use \"-h\" or \"--help\" for more info." >&2
-                        exit 1
-                fi
                 add_currency "$1"
                 shift
                 ;;
 
-            list|list-CURRENCIES|status|profit)
+            list|list-currency|status|profit)
             # checks if a command has already been specified
-                if [ $command_set = 0 ]
+                if [ "$command_set" = 1 ]
                     then
                         echo "ERROR: Only one command is allowed!" >&2
                         exit 1
                 fi
                 COMMAND="$1"
-                command_set=0
-                shift
-                ;;
-
-            *.gz)
-                check_FILES "$1"
-                # send FILES to awk: -P (posix mode) -F (field seperator with parameter)
-                add_file "$1"
-                # echo "$1"
-                shift
-                ;;
-
-            *.log)
-                check_FILES "$1"
-                add_file "$1"
+                if [ "$COMMAND" = "list-currency" ]
+                    then
+                        COMMAND=list_currency
+                fi
+                command_set=1
                 shift
                 ;;
 
             *)
-                TRADER="$1"
+                # uses grep and regex to check the type of the file
+                if echo "$1" | grep -q "\.log$"
+                    then
+                        # sends the contents of the file to the specified command
+                        add_file "$1"
+                        check_all
+                        cat "$1" | $COMMAND
+                elif echo "$1" | grep -q "\.gz$"
+                    then
+                        add_file "$1"
+                        check_all
+                        zcat "$1" | $COMMAND
+                else
+                    if [ "$TRADER" != "" ]
+                        then
+                            echo "ERROR: Max 1 user. Use \"-h\" or \"--help\" for more info." >&2
+                            exit 1
+                    fi
+                    # If a user is not set, set the user
+                    TRADER="$1"
+                fi
                 shift
                 ;;
         esac
     done
 # End of filter parsing
-echo "$CURRENCIES"
-case "$COMMAND" in
-    list) list ;;
-    list-CURRENCIES) list_CURRENCIES ;;
-    status) status ;;
-    profit) profit ;;
-esac
+# echo "$file_count"
+# check_args "$FILES" "$file_error"
 
 # =${XTF_PROFIT:-20} if XTF_PROFIT is not set, then set it to 20
 # skús dať za ten sort ešte | awk 'NF'
@@ -190,10 +241,20 @@ esac
 # TRADER straight to awk? idk
 # time ./test_xtf.sh 2> /dev/null > /dev/null     ||||| na testy rychlosti potom
 # uniq -> proti dupllicitnym riadkom
+# or instead of uniq: sort -u
 # grep na vyberanie specifickych riadkov
 # napr. fgrep -> fast grep, snad moze byt, uvidime
 # cut -> vyberanie stlpcov podla oddelovaca
 # awk is the best for structured FILESs (like columns...)
 # : $1 = 1st column in awk
 # $24tildaAHOJ -> if AHOJ in 24th column, print
+# getline seems useful in awk
 # make seperate function for parsing names and FILESs, then use return to pipe elsewhere
+# set -e  -> should help with exiting parent shell from subshell -> every non-zero exit code turns off the script
+# gzip -de  -> instead of zcat if needed
+# date -d > /dev/null
+# if [ ! -r subor ] -> for checking permissions to a file
+#  if ! Echo file | grep -qE regex  -> for exiting out of awk from a pipeline?
+# '^[0-9]{4}-[0-9]{2}-[0-9]{2}\ [0-9]{2}:[0-9]{2}:[0-9]{2}$'  for date checking -> dat do premennej
+# Asi len empty riadok by som ignoroval, teda \n\n  -> v suboru
+# time ./xtf big_file.log  > /dev/null  -> for checking time, 0.881 is time to beat
